name = "WiringDiagrams"
uuid = "5B9EA594-1203-4FDA-BF59-275F9928902E"
license = "MIT"
authors = ["Richard Samuelson <rsamuelson@ufl.edu.com>"]

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
CliqueTrees = "60701a23-6482-424a-84db-faee86b9b1f8"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"

[extensions]
OMEinsumExt = "OMEinsum"

[compat]
AbstractTrees = "0.4.5"
CliqueTrees = "1.12.2"
Graphs = "1.13.1"
julia = "1.10"
OMEinsum = "0.9.2"
SparseArrays = "1.12.0"
